### ISSUE TITLE
Graphics Example: `image-rendering: pixelated;` doesn't work in Firefox

### ISSUE THREAD

**Issue by starblue** [torch2424/wasm-by-example#116]
To get the desired checkerboard pattern in Firefox 85.0 I had to use `image-rendering: crisp-edges;` instead of `image-rendering: pixelated;`. The latter gave a message `Error in parsing value for ‘image-rendering’.  Declaration dropped.` and showed an interpolated pattern.

**Comment by torch2424** [comment]
Ah, so I think I added both `crisp-edges` and `pixelated` since I think Chrome and firefox differ. But it seems to work for me? :thinking: I'm also on Firefox 85.0 :hushed: 

![Screenshot from 2021-02-04 17-08-18](https://user-images.githubusercontent.com/1448289/106975692-d291be00-670b-11eb-9862-b75f1337abe9.png)

**Comment by starblue** [comment]
For me the issue happened while I was working through the example,
Maybe it should be added there, too?
Here is a screenshot:
![image](https://user-images.githubusercontent.com/3997594/107009437-5b087100-6795-11eb-98ef-432cea6cebae.png)

The web page with both attributes is OK.

**Comment by torch2424** [comment]
@starblue Ahhh! Yeah I probably forgot to update the code with both attributes! My apologies about that! I'll open a PR right now to fix it! :smile:

**Comment by torch2424** [comment]
@starblue This should now be auto deployed! The website uses a service worker, so it may be a little bit before you local caching takes in the new changes. But yeah! Thanks for the issue! :smile: :tada:
